### ISSUE TITLE
pythonrouge

### ISSUE THREAD

**Issue by Ontheroad123** [yuhaozhang/summarize-radiology-findings#2]
I have a question about the pachage:pythonrouge,i have pip it :pip install git+https://github.com/tagucci/pythonrouge.git,but it errored:
File "train.py", line 149, in <module>
    rouge1, rouge2, rougel = rouge.get_rouge(dev_preds, dev_gold, use_cf=False)
  File "/share/users_root/heqiang/summarize-radiology-findings-master/utils/rouge.py", line 29, in get_rouge
    score = rouge.calc_score()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pythonrouge/pythonrouge.py", line 382, in calc_score
    output = subprocess.check_output(rouge_cmd, stderr=subprocess.STDOUT)
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError,
thankyou

**Comment by yuhaozhang** [comment]
It is an error from the pythonrouge package. I have found this seemingly relevant issue on their github page: https://github.com/tagucci/pythonrouge/issues/31

Can you try the proposed solution on the page and see if it works?

**Comment by Ontheroad123** [comment]
I'm sorry to tell you i have failed,my computer is Centos, so i have yum the package what you told,
sudo yum install expat expat-devel -y,but the error is still happened,i found this:
https://rosindex.github.io/d/libexpat1-dev/    ,you can visit this web,
could please provide another pythonrouge package which suit centos system?thankyou

**Comment by Ontheroad123** [comment]
> I'm sorry to tell you i have failed,my computer is Centos, so i have yum the package what you told,
> sudo yum install expat expat-devel -y,but the error is still happened,i found this:
> https://rosindex.github.io/d/libexpat1-dev/ ,you can visit this web,
> could please provide another pythonrouge package which suit centos system?thankyou

I have solved it ,thankyou
https://github.com/tagucci/pythonrouge/issues/31
