### ISSUE TITLE
the problem about README

### ISSUE THREAD

**Issue by Ontheroad123** [yuhaozhang/summarize-radiology-findings#3]
when i implement your code,i found some questions in README
first problem, the train command may be delete '--attn_background',the code in train.py isn't the 
'--attn_background' parameter
next problem, the eval command may be modified,the pretrain model is in './pretrained/model.pt':
python eval.py pretrained --model model.pt --data_dir dataset/$REPORT --dataset test

**Comment by yuhaozhang** [comment]
Hi @Ontheroad123, thanks for capturing this. The `--attn_background` indeed should be removed. This is an old argument that I used for a local version of my code.

For running the pretrained model, yes you should use `--model model.pt`. The example command that I showed was for running evaluation on your own trained models.
