### ISSUE TITLE
Not getting the predictions presented in paper

### ISSUE THREAD

**Issue by ujjwalmachineai** [yuhaozhang/summarize-radiology-findings#4]
After running the pre-trained model and giving background and findings mentioned in Figure 4 of the paper, I am not able to get the summary presented in the paper.

The model is not selecting anything from the background data. Is there any flag to be passed while running run.py for interactive output?

**Comment by Ontheroad123** [comment]
yes,the code is dealed in function 'run.py',you can try more examples.

**Comment by yuhaozhang** [comment]
@ujjwalmachineai It does seem like there is some random effect in the training of the model. Or in other words, the released pretrained model may not get the exactly same result with the result presented in the paper. That said, when I run on my examples locally, the pretrained model does produce many good summaries. Can you try more of your own examples and see if the pretrained model is working well on your data?
